import cx_Oracle

cx_Oracle.init_oracle_client(lib_dir=r"C:\oracle\instantclient_19_14")
connection = cx_Oracle.connect(user="yty_sample", password="Oracle#12345678", dsn="ebiwdb_high")
cursor = connection.cursor()

# Create a table

# cursor.execute("""begin
#                      execute immediate 'drop table yty_machine_log_opcua';
#                      exception when others then if sqlcode <> -942 then raise; end if;
#                   end;""")
cursor.execute("create table yty_machine_log_opcua (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, logged_at TIMESTAMP (2) NOT NULL, temperature float, pressure float, pumpsetting varchar2(20))")

# Insert some rows

# now = datetime.now()
# print("now: ", now) 

# rows = [ (1, "First" ),
#          (2, "Second" ),
#          (3, "Third" ),
#          (4, "Fourth" ),
#          (5, "Fifth" ),
#          (6, "Sixth" ),
#          (7, "Seventh" ) ]

# rows = [ ( LOCALTIMESTAMP(2), 10.1111, 20.1111, "speed" ),
#          (LOCALTIMESTAMP(2), 15.22222, 21.3333333, "speed" ),
#           ]
# cursor.execute("insert into yty_machine_log_opcua(logged_at, temperature, pressure, pumpsetting) values (LOCALTIMESTAMP(2), 10.1111, 20.1111, 'speed')")
# cursor.executemany("insert into yty_machine_log_opcua(logged_at, temperature, pressure, pumpsetting) values (:1, :2, :3, :4)", rows)
# connection.commit()  # uncomment to make data persistent

# # Now query the rows back

# for row in cursor.execute('select * from demo_opcua'):
#     print(row)